frood/urls.py
from django.conf.urls import patterns, url
from frood import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^meetup/(?P<meetup_name_url>\w+)/$', views.meetup, name='meetup'),
        url(r'^meetup/(?P<meetup_name_url>\w+)/join/$', views.meetup_join, name='meetup_join'),
        url(r'^meetup/(?P<meetup_name_url>\w+)/quit/$', views.meetup_quit, name='meetup_quit'),
        url(r'^meetup/(?P<meetup_name_url>\w+)/delete/$', views.meetup_delete, name='meetup_delete'),
        url(r'^add_meetup/(?P<xcor>-?\d+\.\d+)/(?P<ycor>-?\d+\.\d+)/$', views.add_meetup, name='add_meetup'), # NEW MAPPING!
        url(r'^select_location/$', views.select_location, name='select_location'), # NEW MAPPING!
        #url(r'^category/(?P<category_name_url>\w+)/add_page/$', views.add_page, name='add_page'), 
        url(r'^register/$', views.register, name='register'),
        url(r'^restricted/', views.restricted, name='restricted'), #View that requires users to login
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^u/(?P<username>\w+)/$', views.user_profile, name='userprofile'),
        url(r'^u/(?P<tusername>\w+)/add_review/$', views.add_review, name='add_review')
)

froodwip/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'froodwip.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^frood/', include('frood.urls')), 
)

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

frood/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime    

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    interests = models.CharField(max_length = 25)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

# Create your models here.
class Meetup(models.Model):
    xcor = models.FloatField()
    ycor = models.FloatField()
    uid = models.CharField(max_length = 128)
    name = models.CharField(max_length = 25)
    COPAY_CHOICES= (
        ('TEN', '10%'),
        ('TWENTY', '20%'),
        ('THIRTY', '30%'),
        ('FORTY', '40%'),
        ('FIFTY', '50%'),
        ('SIXTY', '60%'),
        ('SEVENTY', '70%'),
        ('EIGHTY', '80%'),
        ('NINETY', '90%'),
        ('HUNDRED', '100%'),
    )
    user = models.ForeignKey(User,related_name="user")
    iuser = models.ManyToManyField(User,related_name="iuser")
    copay = models.CharField(choices = COPAY_CHOICES, max_length = 25)
    datetime = models.DateTimeField()
    #location
    def __unicode__(self):
        return (self.user, self.datetime)

class Review(models.Model):
    fuser = models.ForeignKey(User,related_name="fuser")
    tuser = models.ForeignKey(User,related_name="tuser")
    title = models.CharField(max_length = 25)
    description = models.CharField(max_length = 50)
    def __unicode__(self):
        return (self.title)

frood/forms.py
from django import forms
from frood.models import Meetup, User, UserProfile, Review
from django.contrib.admin import widgets

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('interests', 'picture')

class MeetupForm(forms.ModelForm):

    datetime = forms.DateTimeField(initial='YYYY-MM-DD HH:MM:SS')
    #location

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Meetup
        fields = ('name', 'copay','datetime')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'description')

frood/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect

from frood.models import Meetup, UserProfile, Review
from frood.forms import MeetupForm,ReviewForm
from frood.forms import UserForm, UserProfileForm
from django.contrib.auth.models import User

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required    

from django.utils import simplejson

import hashlib

def decode_url(url):
    return url.replace(' ', '_')
  
def index(request):
    context = RequestContext(request)

    # Query for categories - add the list to our context dictionary.
    meetup_list = Meetup.objects.all()
    loclist=[]
    for meet in meetup_list:
        loclist.append([meet.name,meet.xcor,meet.ycor])
    jsonloc=simplejson.dumps(loclist);
    context_dict = {'meetups': meetup_list,'loc':jsonloc}

    # The following two lines are new.
    # We loop through each category returned, and create a URL attribute.
    # This attribute stores an encoded URL (e.g. spaces replaced with underscores).
    # Render the response and return to the client.
    return render_to_response('frood/index.html', context_dict, context)

    
@login_required 
def meetup(request,meetup_name_url):
    # Request our context from the request passed to us.
    context = RequestContext(request)

    # Create a context dictionary which we can pass to the template rendering engine.
    # We start by containing the name of the category passed by the user.
    context_dict = {'meetup_name_url': meetup_name_url}
    context_dict['meetup_exists'] = False
    try:
        # Can we find a category with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        meetup = Meetup.objects.get(uid=meetup_name_url)
        loclist=[]
        loclist.append([meetup.name,meetup.xcor,meetup.ycor])
        jsonloc=simplejson.dumps(loclist);
        context_dict['loc']=jsonloc
        context_dict['meetup'] = meetup
        context_dict['iusers'] = meetup.iuser.all()
        context_dict['ishost'] = request.user.username == meetup.user.username
        context_dict['isjoin'] = request.user in meetup.iuser.all()
        context_dict['meetup_exists'] = True
    except Meetup.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    # Go render the response and return it to the client.
    return render_to_response('frood/meetup.html', context_dict, context)

@login_required
def meetup_join(request,meetup_name_url):
    context = RequestContext(request)
    #context_dict = {'meetup_name_url': meetup_name_url}
    try:
        meetup = Meetup.objects.get(uid=meetup_name_url)
        if request.user not  in meetup.iuser.all():
            meetup.iuser.add(request.user)
    except Meetup.DoesNotExist:
        pass

    # Redirect
    return HttpResponseRedirect("/frood/meetup/"+meetup.uid+"/#content_block")

@login_required
def meetup_quit(request,meetup_name_url):
    context = RequestContext(request)
    #context_dict = {'meetup_name_url': meetup_name_url}
    try:
        meetup = Meetup.objects.get(uid=meetup_name_url)
        if request.user in meetup.iuser.all():
            meetup.iuser.remove(request.user)
    except Meetup.DoesNotExist:
        pass

    # Redirect
    return HttpResponseRedirect("/frood/meetup/"+meetup.uid+"/#content_block")

@login_required
def meetup_delete(request,meetup_name_url):
    context = RequestContext(request)
    #context_dict = {'meetup_name_url': meetup_name_url}
    try:
        meetup = Meetup.objects.get(uid=meetup_name_url)
        if request.user==meetup.user:
            meetup.delete()
    except Meetup.DoesNotExist:
        pass

    # Redirect
    return HttpResponseRedirect("/frood/")

@login_required
def select_location(request):
    context = RequestContext(request)

    # The following two lines are new.
    # We loop through each category returned, and create a URL attribute.
    # This attribute stores an encoded URL (e.g. spaces replaced with underscores).
    # Render the response and return to the client.
    return render_to_response('frood/select_location.html', {}, context)


@login_required
def add_meetup(request,xcor,ycor):
    # Get the context from the request.
    context = RequestContext(request)

    # A HTTP POST?
    if request.method == 'POST':
        form = MeetupForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            new_meetup = form.save(commit=False) #don't commit first
            user = request.user
            
            hashlink = hashlib.md5()
            hashlink.update(str(user.username).encode('utf-8'))
            hashlink.update(str(Meetup.objects.all().count()).encode('utf-8'))
            
            new_meetup.uid = hashlink.hexdigest()
            new_meetup.xcor=xcor;
            new_meetup.ycor=ycor;
            new_meetup.user=user;
            new_meetup.save() #then save the form

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request)
        else:
            # The supplied form contained errors - just print them to the terminal.
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details.
        form = MeetupForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render_to_response('frood/add_meetup.html', {'form': form,'xcor':xcor,'ycor':ycor}, context)
  
def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render_to_response(
            'frood/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)


from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse  
def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        username = request.POST['username']
        password = request.POST['password']
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            if user.is_active:  # Is the account active? It could have been disabled.
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/frood/')
            else:
                # An inactive account was used - no logging in!
                text = "Your Bookmark account is disabled."
                return render_to_response('frood/failedlogin.html', {'text':text}, context)
        else:
            # Bad login details were provided. So we can't log the user in.

templates/frood/add_meetup.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
        <h2>Add a Meetup</h2>

        <form id="meetup_form" method="post" action="/frood/add_meetup/{{xcor}}/{{ycor}}/">
            
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
				{% if field.errors %}
				<div class="panel panel-danger">
					<div class="panel-heading">
						<h3 class="panel-title">Error(s):</h3>
					</div>
					<div class="panel-body">
						{% for errors in field.errors %}
						<tr>{{ errors }}</tr>
						{% endfor %}
					</div>
				</div>
				{% endif %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field |addcss:"class:form-control" }}          
                </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit" name="submit">Create Meetup</button>
        </form>
{%endblock%}

templates/frood/add_review.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
    <h1>Add a review</h1>
    {% if distinct %}
        <form id="review_form" method="post" action="/frood/u/{{tuser.username}}/add_review/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    {% if field.errors %}
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <h3 class="panel-title">Error(s):</h3>
                        </div>
                        <div class="panel-body">
                            {% for errors in field.errors %}
                            <tr>{{ errors }}</tr>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field |addcss:"class:form-control" }}          
                    </div>
                {% endfor %}
            <button class="btn btn-primary" type="submit" name="submit">Add Review</button>
        </form>
    {% else %}
        <div class="panel panel-danger">
			<div class="panel-heading">
				<h3 class="panel-title">Error: You cannot add a review for yourself</h3>
			</div>
        </div>
    {% endif %}
{%endblock%}

templates/frood/base.html
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Frood</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{STATIC_URL}}bootstrap/css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{STATIC_URL}}bootstrap/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond./js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/frood#content_block">
                    <i class="fa fa-play-circle"></i>  <span class="light">Start</span> Frooding
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    {% if user.is_authenticated %}
                	<li class="page-scroll"><a href="#page-top">Welcome, {{ user.username }}!</a></li>
                	<li class="page-scroll"><a href="/frood/restricted#content_block">Restricted</a></li>
                    <li class="page-scroll"><a href="/frood/select_location#content_block">Add Meetup</a></li>
                    <li class="page-scroll"><a href="/frood/logout#content_block">Logout</a></li>
              		{% else %}
                    <li class="page-scroll">
                        <a href="/frood/register#content_block">Register</a>
                    </li>
                    <li class="page-scroll">
                        <a href="/frood/login#content_block">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Frood</h1>
                        <p class="intro-text">Made simpler with us</p>
                        <a href="#content_block" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Section	 -->
 <header class="intro" id="content_block">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                     {% block body_block%}
        		 	 {% endblock%}
                    </div>
                </div>
            </div>
        </div>
 </header>
{% block map_block%}
{% endblock%}
	<!-- About  -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-6">
                        <h3>Location</h3>
                        <p>One Raffles Institution Lane<br>Singapore 575794</p>
                    </div>
                    
                    <div class="footer-col col-md-6">
                        <h3>About Me</h3>
                        <p>Desperate for CEP Marks</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>

</html>

templates/frood/failedlogin.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
		<h1> Failed Login </h1>
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h3 class="panel-title">Error:</h3>
			</div>
			<div class="panel-body">
				{{ text }}
			</div>
		</div>
{%endblock%}

templates/frood/index.html
{% extends 'frood/base.html' %}
{%load newfilters%}
<!DOCTYPE html>
{%block body_block%}
		{% if meetups %}
		<h1> Meetups </h1>
        <ul class="list-group">
		{% for meetup in meetups %}
            <!-- Following line changed to add an HTML hyperlink -->
            <li class="list-group-item"><a href="/frood/meetup/{{ meetup.uid }}#content_block">{{ meetup.name }}</a></li>
        {% endfor %}
        </ul>
        
		{% else %}
        <div class="panel panel-warning">
			<div class="panel-heading">
				<h3 class="panel-title">There are no Meetups present!</h3>
			</div>
		</div>
        {% endif %}
		
		
		{% if user.is_authenticated %}
           <a class="list-group-item list-group-item-info" href="/frood/select_location#content_block">Add a Meetup</a>
        {% else %}
           <div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">You are not logged in!</h3>
				</div>
			</div>
            <a class="list-group-item list-group-item-success" href="/frood/login#content_block">Login</a>
		    <a class="list-group-item list-group-item-info" href="/frood/register#content_block">Register if you don't have an account</a>
        {% endif %}
{%endblock%}

{% block map_block%}
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      #map_canvas {
        height: 800px;
        width: 100%;
        margin: 0px;
        padding: 0px;
        max-width:none;
        -webkit-box-sizing: content-box;
        -moz-box-sizing: content-box;
        box-sizing: content-box;
      }
      .gmnoprint img {
        max-width: none; 
        }
      img {max-width: none;}
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script>
var locations = {{loc|safe}};
var map;
var initialLocation;
var infowindow = new google.maps.InfoWindow();
var marker, i;
function initialize() {
	if(navigator.geolocation) {
    browserSupportFlag = true;
    navigator.geolocation.getCurrentPosition(function(position) {
    initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
    map.setCenter(initialLocation);
    }, function() {
      handleNoGeolocation(browserSupportFlag);
    });
  }
  var mapOptions = {
    zoom: 10,
    center: new google.maps.LatLng(-33.92, 151.25)
  };
  map = new google.maps.Map(document.getElementById('map_canvas'),
      mapOptions);
	    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map,
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
					infowindow.setContent('<a href='+'/notes/detail/'+locations[i][0]+'>'+locations[i][0]+'</a>');
					infowindow.open(map, marker);
        }
      })(marker, i));
    }
}


google.maps.event.addDomListener(window, 'load', initialize);

   </script>
<div id="map_canvas"></div>
{% endblock%}

templates/frood/login.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
        <h1>Login to Frood</h1>
		<form id="login_form" method="post" action="/frood/login/">
			<ul>
				{% csrf_token %}
				<div class="input-group input-group-lg">
					<input type="text" name="username" value="" size="50" class="form-control" placeholder="Username">
					<span class="input-group-addon">Required</span>
				</div>
				<br />
				<div class="input-group input-group-lg">
					<input type="password" name="password" value="" size="50" class="form-control" placeholder="Password">
					<span class="input-group-addon">Required</span>
				</div>
				<br />
			</ul>
			<button class="btn btn-primary" type="submit" name="submit" value="submit">Submit</button>
        </form>
{%endblock%}

templates/frood/register.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
        <h1>Register with Frood</h1>

        {% if registered %}
           <div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">Welcome, {{ user.username }}! You are already registered.</h3>
				</div>
				<div class="panel-body">
					<a class="list-group-item list-group-item-info" href="/frood/login/#content_block">Return to the homepage.</a><br />
				</div>
			</div>
        {% else %}
		<form id="user_form" method="post" action="/frood/register/"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
			<div class="input-group input-group-lg">
				<input type="text" id="id_username" maxlength="30" name="username" class="form-control" placeholder="Username - 30 characters or fewer.">
				<span class="input-group-addon">Required</span>
			</div>
			<br />
			<div class="input-group input-group-lg">
				<input id="id_email" maxlength="75" name="email" type="email" class="form-control" placeholder="youremail@email.com">
				<span class="input-group-addon">Optional</span>
			</div>
			<br />
			<div class="input-group input-group-lg">
				<input input id="id_password" name="password" type="password" class="form-control" placeholder="Password">
				<span class="input-group-addon">Required</span>
			</div>
			<br />
			<div class="input-group input-group-lg">
				<input id="id_interests" maxlength="200" name="interests" type="text" class="form-control" placeholder="Interests">
				<span class="input-group-addon">Required</span>
			</div>
			<br />
			<div class="input-group input-group-lg">
				<input id="id_picture" name="picture" type="file" class="form-control" placeholder="Choose File">
				<span class="input-group-addon">Optional</span>
			</div>
			<br />

            <!-- Provide a button to click to submit the form. -->
			<button class="btn btn-primary" type="submit" name="submit" value="Register">Register</button>
        </form>
        {% endif %}
{%endblock%}

templates/frood/restricted.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
		<h1> Restricted Content </h1>
        {% if user.is_authenticated %}
		<div class="panel panel-success">
			<div class="panel-heading">
				<h3 class="panel-title">Authenticated:</h3>
			</div>
			<div class="panel-body">
				{{ text }}
			</div>
		</div>
		{% else %}
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h3 class="panel-title">Error:</h3>
			</div>
			<div class="panel-body">
				You are not logged in
			</div>
		</div>
		{% endif %}
{%endblock%}

templates/frood/select_location.html
{% extends 'frood/base.html' %}
{%load newfilters%}
<!DOCTYPE html>
{%block body_block%}
<h1> Drag marker around </h1>
<h1> Double click and click on link when done choosing location of meetup </h1>
{%endblock%}

{% block map_block%}
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      #map_canvas {
        height: 800px;
        width: 100%;
        margin: 0px;
        padding: 0px;
        max-width:none;
        -webkit-box-sizing: content-box;
        -moz-box-sizing: content-box;
        box-sizing: content-box;
      }
      .gmnoprint img {
        max-width: none; 
        }
      img {max-width: none;}
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script>
var map;
var infowindow = new google.maps.InfoWindow();
function initialize() {
  var mapOptions = {
    zoom: 10,
    center: new google.maps.LatLng(-33.92, 151.25)
  };
	map = new google.maps.Map(document.getElementById('map_canvas'),
      mapOptions); 
	var marker = new google.maps.Marker({
		position: mapOptions.center,
		map: map,
		draggable:true,
    title:"Drag me!"
	});
  google.maps.event.addListener(marker, 'dblclick', function() {
    infowindow.setContent('<a href='+'/frood/add_meetup/'+marker.getPosition().lat()+'/'+marker.getPosition().lng()+'/>'+'Submit coordinates'+'</a>');
		infowindow.open(map, marker);
    map.setCenter(marker.getPosition());
  });
  google.maps.event.addListener(marker, 'mouseover', function() {
    infowindow.setContent('<a href='+'/frood/add_meetup/'+marker.getPosition().lat()+'/'+marker.getPosition().lng()+'/>'+'Submit coordinates'+'</a>');
  });
  google.maps.event.addListener(marker, 'mouseout', function() {
    setTimeout(function(){infowindow.close();}, 1000);
  });
}


google.maps.event.addDomListener(window, 'load', initialize);

   </script>

<div id="map_canvas"></div>
{% endblock%}

templates/frood/user_doesnotexist.html
{% extends 'frood/base.html' %}
{%load newfilters%}
{%block body_block%}
		<h1> User Does Not Exist </h1>
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h3 class="panel-title">Error:</h3>
			</div>
			<div class="panel-body">
				{{ text }}
			</div>
		</div>
{%endblock%}